# Generated by Django 4.2.7 on 2023-11-24 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_img', models.FileField(default='image.jpg', upload_to='documents')),
                ('course_name', models.CharField(max_length=30)),
                ('course_content', models.TextField()),
            ],
        ),
    ]
